import asyncio


def test_all_expected_mcp_tools_register():
    from src import server

    server.register_all_tools()
    registered = {tool.name for tool in asyncio.run(server.mcp.list_tools())}

    assert {
        "fdtd_health",
        "fdtd_session_start",
        "fdtd_session_pause",
        "fdtd_session_close",
        "fdtd_save",
        "fdtd_load",
        "fdtd_add_fdtd_region",
        "fdtd_add_rect",
        "fdtd_add_circle",
        "fdtd_simulation_plan_validate",
        "fdtd_simulation_plan_approve",
        "fdtd_simulation_plan_start",
        "fdtd_simulation_plan_real_preflight",
        "fdtd_simulation_plan_production_preflight",
        "fdtd_job_plan",
        "fdtd_job_start",
        "fdtd_job_status",
        "fdtd_job_tasks",
        "fdtd_job_resume",
        "fdtd_metasurface_sweep_plan",
        "fdtd_metasurface_sweep_start",
        "fdtd_sweep_config_get",
        "fdtd_sweep_config_set",
        "fdtd_sweep_run",
        "fdtd_sweep_status",
        "fdtd_sweep_monitor",
        "fdtd_results_list",
        "fdtd_results_download",
        "fdtd_export_gds",
        "fdtd_export_data",
        "fdtd_device_template",
        "fdtd_list_devices",
        "fdtd_troubleshoot",
        "fdtd_best_practices",
    } == registered


EXPECTED_DELIVERABLE_TOOLS = {
    "fdtd_health",
    "fdtd_session_start",
    "fdtd_session_pause",
    "fdtd_session_close",
    "fdtd_project_new",
    "fdtd_project_load",
    "fdtd_project_save",
    "fdtd_project_status",
    "fdtd_switch_to_layout",
    "fdtd_object_create",
    "fdtd_object_list",
    "fdtd_object_get",
    "fdtd_object_update",
    "fdtd_object_copy",
    "fdtd_object_rename",
    "fdtd_object_delete",
    "fdtd_group_update",
    "fdtd_material_create",
    "fdtd_material_list",
    "fdtd_material_get",
    "fdtd_material_update",
    "fdtd_material_assign",
    "fdtd_material_fit_diagnose",
    "fdtd_solver_get",
    "fdtd_solver_update",
    "fdtd_mesh_diagnose",
    "fdtd_resource_estimate",
    "fdtd_source_create",
    "fdtd_source_get",
    "fdtd_source_update",
    "fdtd_monitor_create",
    "fdtd_monitor_get",
    "fdtd_monitor_update",
    "fdtd_analysis_group_create",
    "fdtd_analysis_group_get",
    "fdtd_analysis_group_update",
    "fdtd_simulation_run",
    "fdtd_simulation_status",
    "fdtd_result_list",
    "fdtd_result_describe",
    "fdtd_result_read",
    "fdtd_results_download",
    "fdtd_export_gds",
    "fdtd_export_data",
    "fdtd_eval",
    "fdtd_getv",
    "fdtd_setv",
    "fdtd_device_recipe_validate",
    "fdtd_device_recipe_compile",
    "fdtd_device_recipe_build",
    "fdtd_generic_sweep_validate",
    "fdtd_generic_sweep_plan",
    "fdtd_generic_sweep_start",
    "fdtd_simulation_plan_validate",
    "fdtd_simulation_plan_approve",
    "fdtd_simulation_plan_start",
    "fdtd_simulation_plan_real_preflight",
    "fdtd_simulation_plan_production_preflight",
    "fdtd_job_plan",
    "fdtd_job_start",
    "fdtd_job_status",
    "fdtd_job_tasks",
    "fdtd_job_resume",
    "fdtd_metasurface_sweep_plan",
    "fdtd_metasurface_sweep_start",
    "fdtd_device_template",
    "fdtd_list_devices",
    "fdtd_troubleshoot",
    "fdtd_best_practices",
}


def test_deliverable_tool_registry_exact():
    from src import server

    tool_names = set(server.collect_registered_tool_names_for_tests())
    assert tool_names == EXPECTED_DELIVERABLE_TOOLS
    assert not {name for name in tool_names if name.startswith("fdtd_sweep_")}
