param(
    [string]$ConnectionMode = "ssh",
    [string]$LumericalPython = "",
    [string]$LumapiPath = "",
    [string]$RpcHost = "127.0.0.1",
    [int]$RpcPort = 5000,
    [string]$JobRoot = "",
    [switch]$Help
)

$ErrorActionPreference = "Stop"

if ($Help) {
    @"
FDTD MCP Windows RPC Setup

Usage: setup_rpc.ps1 [-ConnectionMode ssh|lan] [-LumericalPython <path>]
       [-LumapiPath <path>] [-RpcHost <host>] [-RpcPort <port>]
       [-JobRoot <path>] [-Help]

Options:
  -ConnectionMode    Network mode: ssh (SSH tunnel) or lan (LAN direct)
  -LumericalPython   Path to Lumerical Python executable
  -LumapiPath        Path to lumapi API directory
  -RpcHost           RPC server listen host (default: 127.0.0.1)
  -RpcPort           RPC server listen port (default: 5000)
  -JobRoot           Job storage root directory
  -Help              Show this help
"@
    exit 0
}

$StateRoot = Join-Path $env:LOCALAPPDATA "fdtd-mcp"
$ConfigDir = Join-Path $StateRoot "config"
$RunDir = Join-Path $StateRoot "run"
$LogDir = Join-Path $StateRoot "logs"
$ConfigFile = Join-Path $ConfigDir "rpc.env"

Write-Host "=== FDTD MCP Windows RPC Setup ==="
Write-Host "State directory: $StateRoot"

# Create directories
New-Item -ItemType Directory -Force -Path $ConfigDir, $RunDir, $LogDir | Out-Null

# Detect Lumerical Python
if (-not $LumericalPython) {
    $candidates = @(
        "F:\Program Files\Lumerical\v242\python\python.exe",
        "C:\Program Files\Lumerical\v242\python\python.exe",
        "C:\Program Files\ANSYS Inc\v242\python\python.exe"
    )
    foreach ($cand in $candidates) {
        if (Test-Path $cand) {
            $LumericalPython = $cand
            break
        }
    }
}

if (-not $LumericalPython -or -not (Test-Path $LumericalPython)) {
    throw "Lumerical Python not found. Please specify with -LumericalPython."
}
Write-Host "Lumerical Python: $LumericalPython"

# Detect Pythonw
$PythonDir = Split-Path $LumericalPython -Parent
$Pythonw = Join-Path $PythonDir "pythonw.exe"
if (-not (Test-Path $Pythonw)) {
    $Pythonw = $LumericalPython
}
Write-Host "Background launcher: $Pythonw"

# Verify lumapi
if (-not $LumapiPath) {
    $LumapiPath = Join-Path (Split-Path $PythonDir -Parent) "api\python"
}
Write-Host "Lumapi path: $LumapiPath"

$verifyCmd = "import sys; sys.path.insert(0, '$LumapiPath'); import lumapi; print('OK')"
$verifyResult = & $LumericalPython -c $verifyCmd 2>&1
if ($verifyResult -notmatch "OK") {
    Write-Host "[WARN] lumapi verification returned: $verifyResult"
    Write-Host "       Setup will continue but RPC may fail to import lumapi."
} else {
    Write-Host "lumapi verification: OK"
}

# Auto-detect JobRoot if not specified
if (-not $JobRoot) {
    $scriptDir = Split-Path $PSCommandPath -Parent
    $projectRoot = (Resolve-Path (Join-Path $scriptDir "..\..")).Path
    $JobRoot = Join-Path $projectRoot "jobs"
}
Write-Host "Job root: $JobRoot"

# Write config (exclude FDTD_FEISHU_WEBHOOK)
$configContent = @"
# FDTD MCP RPC configuration — generated by setup_rpc.ps1
# Do not store secrets here.
FDTD_PYTHON=$LumericalPython
LUMAPI_PATH=$LumapiPath
FDTD_RPC_HOST=$RpcHost
FDTD_RPC_PORT=$RpcPort
FDTD_JOB_ROOT=$JobRoot
CONNECTION_MODE=$ConnectionMode
STATE_ROOT=$StateRoot
"@

Set-Content -LiteralPath $ConfigFile -Value $configContent.Trim() -NoNewline
Write-Host "Configuration written: $ConfigFile"

# Firewall rule for LAN mode
if ($ConnectionMode -eq "lan") {
    $ruleName = "FDTD MCP RPC (TCP $RpcPort)"
    $existing = Get-NetFirewallRule -DisplayName $ruleName -ErrorAction SilentlyContinue
    if (-not $existing) {
        New-NetFirewallRule `
            -DisplayName $ruleName `
            -Direction Inbound `
            -Protocol TCP `
            -LocalPort $RpcPort `
            -Action Allow `
            -Profile Private `
            | Out-Null
        Write-Host "Firewall rule added: $ruleName"
    } else {
        Write-Host "Firewall rule exists: $ruleName"
    }
}

Write-Host "Setup complete. Next steps:"
Write-Host "  1. Ensure FDTD_FEISHU_WEBHOOK is set in user environment (not in rpc.env)"
Write-Host "  2. Run: scripts\windows\restart_rpc.bat"
Write-Host "  3. Verify: curl http://${RpcHost}:$RpcPort/health"
