"""Results and export tools for FDTD MCP Server.

Matches the Windows RPC /results endpoints: list and download output files.
"""

from typing import Optional

from mcp.server.fastmcp import FastMCP

from ..rpc_client.client import RpcClient


def register_analysis_tools(mcp: FastMCP, rpc: RpcClient) -> None:
    """Register results and export tools."""

    @mcp.tool()
    def fdtd_results_list() -> dict:
        """
        List all result files generated by sweeps.

        Returns files organized by directory:
        - results/: Sweep_Results.mat (raw S-parameter data)
        - figures/: Transmission.svg, Dephasing.svg, and .fig files

        Returns:
            {"ok": true, "files": {"results": [...], "figures": [...]}}
        """
        return rpc.results_list()

    @mcp.tool()
    def fdtd_results_download(filepath: str, save_to: Optional[str] = None) -> dict:
        """
        Download a result file from the Windows machine to your local Mac.

        Common files:
          - "figures/Transmission.svg" — Transmission heatmap
          - "figures/Dephasing.svg" — Dephasing heatmap
          - "results/Sweep_Results.mat" — Raw S-parameter data (MATLAB .mat)

        Args:
            filepath: Path relative to the Windows workspace, e.g. "figures/Transmission.svg".
            save_to: Local path to save. Defaults to the file's basename in current directory.

        Returns:
            {"ok": true, "saved_to": "/local/path/Transmission.svg"}
        """
        return rpc.results_download(filepath, save_to)
